## NAIVE GAUSSIAN ELIMINATION

In [2]:
import numpy as np

In [3]:
def gauss_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)
    print("Augmented matrix awal:")
    print(np.column_stack((A, b)))

    # Forward elimination
    for i in range(n-1):
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j] -= factor * A[i]
            b[j] -= factor * b[i]
            print(f"R{j+1} = R{j+1} - ({factor:.3f})R{i+1}")
            print(np.column_stack((A, b)))

    # Back Substitution V1 Sesuai Pseudocode
    x = np.zeros(n)
    x[n-1] = b[n-1] / A[n-1][n-1] # Elemen terakhir
    for i in range(n-2, -1, -1): 
        sum_val = b[i]
        for j in range(i+1, n):
            sum_val = sum_val - A[i][j] * x[j] 
        x[i] = sum_val / A[i][i]
    
    # Back substitution V2 (lebih sederhana)
    # x = np.zeros(n)
    # for i in range(n-1, -1, -1):
    #     x[i] = (b[i] - np.dot(A[i][i+1:], x[i+1:])) / A[i][i]

    
    return x

### Contoh 1
Diberikan sistem persamaan
$$x_1+2x_2+3x_3=8$$
$$2x_1+3x_2+2x_3=10$$
$$3x_1+x_2+2x_3=7$$
Dapat dituliskan sebagai:
$$A= \begin{bmatrix}
 1 & 2 & 3  \\
 2 & 3 & 2 \\
 3 & 1 & 2
\end{bmatrix},
b= \begin{bmatrix}
 8 \\
 10 \\
 7 \\
\end{bmatrix}
$$

In [6]:
A1 = np.array([[1, 2, 3],
              [2, 3, 2],
              [3, 1, 2]
              ])
b1 = np.array([8, 10, 7])

x = gauss_elimination(A1, b1)
print("\nSolusi Akhir:")
print(f"x1 = {x[0]:.4f}")
print(f"x2 = {x[1]:.4f}")
print(f"x3 = {x[2]:.4f}")


Augmented matrix awal:
[[ 1.  2.  3.  8.]
 [ 2.  3.  2. 10.]
 [ 3.  1.  2.  7.]]
R2 = R2 - (2.000)R1
[[ 1.  2.  3.  8.]
 [ 0. -1. -4. -6.]
 [ 3.  1.  2.  7.]]
R3 = R3 - (3.000)R1
[[  1.   2.   3.   8.]
 [  0.  -1.  -4.  -6.]
 [  0.  -5.  -7. -17.]]
R3 = R3 - (5.000)R2
[[ 1.  2.  3.  8.]
 [ 0. -1. -4. -6.]
 [ 0.  0. 13. 13.]]

Solusi Akhir:
x1 = 1.0000
x2 = 2.0000
x3 = 1.0000


### Contoh 2

In [5]:
A1 = np.array([[6, -2, 2, 4],
               [12, -8, 6, 10],
               [3, -13, 9, 3],
               [-6, 4, 1, -18]
              ])
b1 = np.array([16, 26, -19, -34])

x = gauss_elimination(A1, b1)

print("\nSolusi Akhir:")
print(f"x1 = {x[0]:.4f}")
print(f"x2 = {x[1]:.4f}")
print(f"x3 = {x[2]:.4f}")
print(f"x4 = {x[3]:.4f}")


Augmented matrix awal:
[[  6.  -2.   2.   4.  16.]
 [ 12.  -8.   6.  10.  26.]
 [  3. -13.   9.   3. -19.]
 [ -6.   4.   1. -18. -34.]]
R2 = R2 - (2.000)R1
[[  6.  -2.   2.   4.  16.]
 [  0.  -4.   2.   2.  -6.]
 [  3. -13.   9.   3. -19.]
 [ -6.   4.   1. -18. -34.]]
R3 = R3 - (0.500)R1
[[  6.  -2.   2.   4.  16.]
 [  0.  -4.   2.   2.  -6.]
 [  0. -12.   8.   1. -27.]
 [ -6.   4.   1. -18. -34.]]
R4 = R4 - (-1.000)R1
[[  6.  -2.   2.   4.  16.]
 [  0.  -4.   2.   2.  -6.]
 [  0. -12.   8.   1. -27.]
 [  0.   2.   3. -14. -18.]]
R3 = R3 - (3.000)R2
[[  6.  -2.   2.   4.  16.]
 [  0.  -4.   2.   2.  -6.]
 [  0.   0.   2.  -5.  -9.]
 [  0.   2.   3. -14. -18.]]
R4 = R4 - (-0.500)R2
[[  6.  -2.   2.   4.  16.]
 [  0.  -4.   2.   2.  -6.]
 [  0.   0.   2.  -5.  -9.]
 [  0.   0.   4. -13. -21.]]
R4 = R4 - (2.000)R3
[[ 6. -2.  2.  4. 16.]
 [ 0. -4.  2.  2. -6.]
 [ 0.  0.  2. -5. -9.]
 [ 0.  0.  0. -3. -3.]]

Solusi Akhir:
x1 = 3.0000
x2 = 1.0000
x3 = -2.0000
x4 = 1.0000
