# Gauss Jordan

In [9]:
import numpy as np

def gauss_jordan_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

    print("Augmented matrix awal:")
    print(np.column_stack((A, b)))

    for i in range(n):
        # Normalisasi pivot
        pivot = A[i, i]
        A[i] /= pivot
        b[i] /= pivot
        print(f"\nR{i+1} = R{i+1} / {pivot}")

        # Eliminasi baris lain
        for j in range(n):
            if j != i:
                factor = A[j, i]
                A[j] -= factor * A[i]
                b[j] -= factor * b[i]
                print(f"R{j+1} = R{j+1} - ({factor})R{i+1}")

        print(np.column_stack((A, b)))

    print("\nHasil akhir:")
    print(np.column_stack((A, b)))

    return b

### Contoh 1
Diberikan sistem persamaan dalam bentuk matriks
$$A= \begin{bmatrix}
 2 & -2 & 2  \\
 4 & 2 & -1 \\
 2 & -2 & 4
\end{bmatrix},
b= \begin{bmatrix}
 0 \\
 7 \\
 2 \\
\end{bmatrix}
$$

In [10]:
A1 = np.array([[2, -2, 2],
               [4, 2, -1],
               [2, -2, 4]
              ])
b1 = np.array([0, 7, 2]) 

x = gauss_jordan_elimination(A1, b1)

print("\nSolusi x:")
print(x)


Augmented matrix awal:
[[ 2. -2.  2.  0.]
 [ 4.  2. -1.  7.]
 [ 2. -2.  4.  2.]]

R1 = R1 / 2.0
R2 = R2 - (4.0)R1
R3 = R3 - (2.0)R1
[[ 1. -1.  1.  0.]
 [ 0.  6. -5.  7.]
 [ 0.  0.  2.  2.]]

R2 = R2 / 6.0
R1 = R1 - (-1.0)R2
R3 = R3 - (0.0)R2
[[ 1.          0.          0.16666667  1.16666667]
 [ 0.          1.         -0.83333333  1.16666667]
 [ 0.          0.          2.          2.        ]]

R3 = R3 / 2.0
R1 = R1 - (0.16666666666666663)R3
R2 = R2 - (-0.8333333333333334)R3
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 1.]]

Hasil akhir:
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 1.]]

Solusi x:
[1. 2. 1.]
