# Gauss Elimintaion with Scaled Partial Pivoting

In [5]:
import numpy as np

def gaussian_elimination_spp(A, b):
    n = len(b)
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    L = np.arange(n) #L=[0, 1, 2, 3, ...]
    S = np.max(np.abs(A), axis=1)
    print(np.column_stack((A, b)))

    for k in range(n - 1):
        # 1. Pemilihan Poros
        ratios = np.abs(A[L[k:], k]) / S[L[k:]]
        best_row_index_relative = np.argmax(ratios)
        best_row_index_absolute = best_row_index_relative + k
        L[k], L[best_row_index_absolute] = L[best_row_index_absolute], L[k]
        print(
            f"Kolom {k+1}\n" f"Rasio: {ratios}\n"
            f"Pivot: {L[best_row_index_absolute]+1} (rasio: {ratios[best_row_index_relative]})\n"
            f"Swap baris {L[k]+1} dengan baris {L[best_row_index_absolute]+1}\n"
            f"Vektor L setelah swap: {L+1}\n"
        )
        # 2. Proses Eliminasi
        for i in range(k + 1, n):
            multiplier = A[L[i], k] / A[L[k], k]
            for j in range(k, n):
                A[L[i], j] = A[L[i], j] - (multiplier * A[L[k], j])
            b[L[i]] = b[L[i]] - (multiplier * b[L[k]])
        print(np.column_stack((A, b)))
        
    # 3. Back Sustitution
    x = np.zeros(n)
    x[n - 1] = b[L[n - 1]] / A[L[n - 1], n - 1]
    for i in range(n - 2, -1, -1):
        sum_ax = 0
        for j in range(i + 1, n):
            sum_ax += A[L[i], j] * x[j]
        x[i] = (b[L[i]] - sum_ax) / A[L[i], i]
    return x, L, S


### Contoh 1
Diberikan sistem persamaan dalam bentuk matriks
$$
\begin{bmatrix}
1 & -1 & 2 & 1 \\
3 & 2 & 1 & 4 \\
5 & 8 & 6 & 3 \\
4 & 2 & 5 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
x_4
\end{bmatrix}
=
\begin{bmatrix}
1\\
1\\
1\\
-1
\end{bmatrix}
$$

In [6]:
A2 = [
    [1, -1, 2, 1],
    [3, 2, 1, 4],
    [5, 8, 6, 3],
    [4, 2, 5, 3]
]
b2 = [1, 1, 1, -1]

# Menjalankan fungsi
x, L, S = gaussian_elimination_spp(A2, b2)

# Menampilkan Hasil
print("=== HASIL PERHITUNGAN ===")
print(f"Vektor Skala S: {S}")
# Tambah 1 ke L agar tampilannya (1-based) sama dengan di gambar
print(f"Vektor Indeks L Akhir: {L + 1}") 
print("\nSolusi Akhir:")
print(f"x1 = {x[0]:.4f}")
print(f"x2 = {x[1]:.4f}")
print(f"x3 = {x[2]:.4f}")
print(f"x4 = {x[3]:.4f}")

[[ 1. -1.  2.  1.  1.]
 [ 3.  2.  1.  4.  1.]
 [ 5.  8.  6.  3.  1.]
 [ 4.  2.  5.  3. -1.]]
Kolom 1
Rasio: [0.5   0.75  0.625 0.8  ]
Pivot: 1 (rasio: 0.8)
Swap baris 4 dengan baris 1
Vektor L setelah swap: [4 2 3 1]

[[ 0.   -1.5   0.75  0.25  1.25]
 [ 0.    0.5  -2.75  1.75  1.75]
 [ 0.    5.5  -0.25 -0.75  2.25]
 [ 4.    2.    5.    3.   -1.  ]]
Kolom 2
Rasio: [0.125  0.6875 0.75  ]
Pivot: 2 (rasio: 0.75)
Swap baris 1 dengan baris 2
Vektor L setelah swap: [4 1 3 2]

[[ 0.         -1.5         0.75        0.25        1.25      ]
 [ 0.          0.         -2.5         1.83333333  2.16666667]
 [ 0.          0.          2.5         0.16666667  6.83333333]
 [ 4.          2.          5.          3.         -1.        ]]
Kolom 3
Rasio: [0.3125 0.625 ]
Pivot: 3 (rasio: 0.625)
Swap baris 2 dengan baris 3
Vektor L setelah swap: [4 1 2 3]

[[ 0.         -1.5         0.75        0.25        1.25      ]
 [ 0.          0.         -2.5         1.83333333  2.16666667]
 [ 0.          0.          0. 

### Contoh 2
Diberikan sistem persamaan dalam bentuk matriks
$$
\begin{bmatrix}
1 & -1 & 2 & 1 \\
3 & 2 & 1 & 4 \\
5 & -8 & 6 & 3 \\
4 & 2 & 5 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
x_4
\end{bmatrix}
=
\begin{bmatrix}
1\\
1\\
1\\
-1
\end{bmatrix}
$$

In [7]:
A3 = [
    [1, -1, 2, 1],
    [3, 2, 1, 4],
    [5, -8, 6, 3],
    [4, 2, 5, 3]
]
b3 = [1, 1, 1, -1]

# Menjalankan fungsi
x, L, S = gaussian_elimination_spp(A3, b3)

# Menampilkan Hasil
print("=== HASIL PERHITUNGAN ===")
print(f"Vektor Skala S: {S}")
# Tambah 1 ke L agar tampilannya (1-based) sama dengan di gambar
print(f"Vektor Indeks L Akhir: {L + 1}") 
print("\nSolusi Akhir:")
print(f"x1 = {x[0]:.4f}")
print(f"x2 = {x[1]:.4f}")
print(f"x3 = {x[2]:.4f}")
print(f"x4 = {x[3]:.4f}")

[[ 1. -1.  2.  1.  1.]
 [ 3.  2.  1.  4.  1.]
 [ 5. -8.  6.  3.  1.]
 [ 4.  2.  5.  3. -1.]]
Kolom 1
Rasio: [0.5   0.75  0.625 0.8  ]
Pivot: 1 (rasio: 0.8)
Swap baris 4 dengan baris 1
Vektor L setelah swap: [4 2 3 1]

[[  0.    -1.5    0.75   0.25   1.25]
 [  0.     0.5   -2.75   1.75   1.75]
 [  0.   -10.5   -0.25  -0.75   2.25]
 [  4.     2.     5.     3.    -1.  ]]
Kolom 2
Rasio: [0.125  1.3125 0.75  ]
Pivot: 2 (rasio: 1.3125)
Swap baris 3 dengan baris 2
Vektor L setelah swap: [4 3 2 1]

[[  0.           0.           0.78571429   0.35714286   0.92857143]
 [  0.           0.          -2.76190476   1.71428571   1.85714286]
 [  0.         -10.5         -0.25        -0.75         2.25      ]
 [  4.           2.           5.           3.          -1.        ]]
Kolom 3
Rasio: [0.69047619 0.39285714]
Pivot: 2 (rasio: 0.6904761904761905)
Swap baris 2 dengan baris 2
Vektor L setelah swap: [4 3 2 1]

[[  0.           0.           0.           0.84482759   1.45689655]
 [  0.           0.      