# Tugas: Jacobi Iteration & Gauss-Seidel
Suatu persamaan linear: 
$$x+8y-2z=-9$$
$$-2x+4y-9z=-50$$
$$10x-3y+6z=24,5$$
Dapat dituliskan sebagai:
$$A= \begin{bmatrix}
 1 & 8 & -2  \\
 -2 & 4 & -9 \\
 10 & -3 & 6
\end{bmatrix},
b= \begin{bmatrix}
 -9 \\
 -50 \\
 24,5 \\
\end{bmatrix}
$$
Hitung nilai $x, y,$ dan $z$ dengan menggunakan:
* a. Metode eliminasi gauss
* b. Metode Gauss Jordan
* c. Metode Iterasi Jacobi
* d. Metode Iterasi Gauss-Seidel

In [1]:
# LIBRARY
import numpy as np
# DEFINISIKAN MATRIKS
A = np.array([
    [1, 8, -2],
    [-2, 4, -9],
    [10, -3, 6]], dtype=float)
b = np.array([-9, -50, 24.5], dtype=float)

## a. Metode Eliminasi Gauss

In [2]:
def gauss_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)
    print("Augmented matrix awal:")
    print(np.column_stack((A, b)))

    # Forward elimination
    for i in range(n-1):
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j] -= factor * A[i]
            b[j] -= factor * b[i]
            print(f"R{j+1} = R{j+1} - ({factor:.3f})R{i+1}")
        print(np.column_stack((A, b)))

    # Back Substitution V1 Sesuai Pseudocode
    x = np.zeros(n)
    x[n-1] = b[n-1] / A[n-1][n-1] # Elemen terakhir
    for i in range(n-2, -1, -1): 
        sum_val = b[i]
        for j in range(i+1, n):
            sum_val = sum_val - A[i][j] * x[j] 
        x[i] = sum_val / A[i][i]
    
    return x

In [3]:
x = gauss_elimination(A, b)
print("\nSolusi Akhir:")
print(f"x1 = {x[0]:.4f}")
print(f"x2 = {x[1]:.4f}")
print(f"x3 = {x[2]:.4f}")


Augmented matrix awal:
[[  1.    8.   -2.   -9. ]
 [ -2.    4.   -9.  -50. ]
 [ 10.   -3.    6.   24.5]]
R2 = R2 - (-2.000)R1
R3 = R3 - (10.000)R1
[[  1.    8.   -2.   -9. ]
 [  0.   20.  -13.  -68. ]
 [  0.  -83.   26.  114.5]]
R3 = R3 - (-4.150)R2
[[   1.      8.     -2.     -9.  ]
 [   0.     20.    -13.    -68.  ]
 [   0.      0.    -27.95 -167.7 ]]

Solusi Akhir:
x1 = -1.0000
x2 = 0.5000
x3 = 6.0000


## b. Metode Gauss-Jordan

In [4]:
def gauss_jordan_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

    print("Augmented matrix awal:")
    print(np.column_stack((A, b)))

    for i in range(n):
        # Normalisasi pivot
        pivot = A[i, i]
        A[i] /= pivot
        b[i] /= pivot
        print(f"\nR{i+1} = R{i+1} / {pivot}")

        # Eliminasi baris lain
        for j in range(n):
            if j != i:
                factor = A[j, i]
                A[j] -= factor * A[i]
                b[j] -= factor * b[i]
                print(f"R{j+1} = R{j+1} - ({factor})R{i+1}")

        print(np.column_stack((A, b)))

    print("\nHasil akhir:")
    print(np.column_stack((A, b)))

    return b

In [5]:
x = gauss_jordan_elimination(A, b)
print("\nSolusi Akhir:")
print(f"x1 = {x[0]:.4f}")
print(f"x2 = {x[1]:.4f}")
print(f"x3 = {x[2]:.4f}")


Augmented matrix awal:
[[  1.    8.   -2.   -9. ]
 [ -2.    4.   -9.  -50. ]
 [ 10.   -3.    6.   24.5]]

R1 = R1 / 1.0
R2 = R2 - (-2.0)R1
R3 = R3 - (10.0)R1
[[  1.    8.   -2.   -9. ]
 [  0.   20.  -13.  -68. ]
 [  0.  -83.   26.  114.5]]

R2 = R2 / 20.0
R1 = R1 - (8.0)R2
R3 = R3 - (-83.0)R2
[[   1.      0.      3.2    18.2 ]
 [   0.      1.     -0.65   -3.4 ]
 [   0.      0.    -27.95 -167.7 ]]

R3 = R3 / -27.950000000000003
R1 = R1 - (3.2)R3
R2 = R2 - (-0.65)R3
[[ 1.   0.   0.  -1. ]
 [ 0.   1.   0.   0.5]
 [-0.  -0.   1.   6. ]]

Hasil akhir:
[[ 1.   0.   0.  -1. ]
 [ 0.   1.   0.   0.5]
 [-0.  -0.   1.   6. ]]

Solusi Akhir:
x1 = -1.0000
x2 = 0.5000
x3 = 6.0000


## c. Metode Iterasi Jacobi

In [6]:
def diagonally_dominant(A,b):
    A = A.copy()
    b = b.copy()
    n = len(b) 
    for i in range(n):
        max_row = i + np.argmax(np.abs(A[i:, i]))
        if max_row != i:
            A[[i, max_row]] = A[[max_row, i]]
            b[[i, max_row]] = b[[max_row, i]]
    print("Setelah diagonally dominant:")
    print(np.column_stack((A, b)))
    return A,b

In [7]:
def jacobi_iteration(A, b, x, tol=1e-2, max_iter=100):
    print("Matirks Awal:")
    print(np.column_stack((A,b)))
    n = len(b)
    #swap row agar diagonally dominant
    A, b = diagonally_dominant(A,b)
    print(f"{'Iter':>4} | {'x1':>8} {'x2':>8} {'x3':>8} | {'%ex1':>8} {'%ex2':>8} {'%ex3':>8}")
    for k in range(max_iter):
        x_new = np.zeros(n)
        for i in range(n):
            s = np.sum(A[i,:] * x) - A[i,i] * x[i] # Jumlahan aij*xj kecuali diagonalnya. 
            x_new[i] = (b[i] - s) / A[i,i] #simpan di x_new
        
        # Hitung Error
        abs_error = np.abs(x_new - x)
        rel_er = (abs_error / np.abs(x_new)) * 100
        print(f"{k+1:4d} | {x_new[0]:8.4f} {x_new[1]:8.4f} {x_new[2]:8.4f} | "f"{rel_er[0]:8.4f} {rel_er[1]:8.4f} {rel_er[2]:8.4f}")
        if np.max(abs_error) < tol:
            print("\nConverged.")
            return x_new
        #update
        x = x_new
    return x

In [8]:
#Nilai tebakan awal
x0 = np.zeros(3)
solution = jacobi_iteration(A, b, x0)

print("\nSolusi:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])

Matirks Awal:
[[  1.    8.   -2.   -9. ]
 [ -2.    4.   -9.  -50. ]
 [ 10.   -3.    6.   24.5]]
Setelah diagonally dominant:
[[ 10.   -3.    6.   24.5]
 [  1.    8.   -2.   -9. ]
 [ -2.    4.   -9.  -50. ]]
Iter |       x1       x2       x3 |     %ex1     %ex2     %ex3
   1 |   2.4500  -1.1250   5.5556 | 100.0000 100.0000 100.0000
   2 |  -1.2208  -0.0424   4.5111 | 300.6826 2555.7377  23.1527
   3 |  -0.2694   0.1554   5.8080 | 353.2096 127.2626  22.3297
   4 |  -0.9882   0.3607   5.6845 |  72.7408  56.9195   2.1735
   5 |  -0.8525   0.4196   5.9355 |  15.9204  14.0514   4.2285
   6 |  -0.9854   0.4654   5.9315 |  13.4871   9.8363   0.0666
   7 |  -0.9693   0.4810   5.9814 |   1.6616   3.2480   0.8339
   8 |  -0.9945   0.4915   5.9847 |   2.5380   2.1275   0.0562
   9 |  -0.9934   0.4955   5.9950 |   0.1125   0.8065   0.1711
  10 |  -0.9984   0.4979   5.9965 |   0.4963   0.4869   0.0255

Converged.

Solusi:
x = -0.9983530472099759
y = 0.4979262587647424
z = 5.9965337310179


## d. Metode Gauss-Seidel

In [11]:
def diagonally_dominant(A,b):
    A = A.copy()
    b = b.copy()
    n = len(b)
    for i in range(n):
        max_row = i + np.argmax(np.abs(A[i:, i]))
        if max_row != i:
            A[[i, max_row]] = A[[max_row, i]]
            b[[i, max_row]] = b[[max_row, i]]
    print("Diagonally dominant:")
    print(np.column_stack((A, b)))
    return A,b

In [12]:
# Gauss Seidel
def gauss_seidel_iteration(A, b, x, tol=1e-2, max_iter=100):
    n = len(b)
    A, b = diagonally_dominant(A,b)
    print(f"{'Iter':>4} | {'x1':>8} {'x2':>8} {'x3':>8} | {'%ex1':>8} {'%ex2':>8} {'%ex3':>8}")

    for k in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            s = np.sum(A[i,:] * x) - A[i,i] * x[i]
            x[i] = (b[i] - s) / A[i,i] #simpan di x, langsung di pakai iter selanjtunya.

        # hitung error
        abs_error = np.abs(x - x_old)
        rel_er = (abs_error / np.abs(x)) * 100
        print(f"{k+1:4d} | {x[0]:8.4f} {x[1]:8.4f} {x[2]:8.4f} | "f"{rel_er[0]:8.4f} {rel_er[1]:8.4f} {rel_er[2]:8.4f}")
        if np.max(abs_error) < tol:
            print("\nConverged.")
            return x

    return x

In [13]:
#Nilai tebakan awal
x0 = np.zeros(3)
solution = gauss_seidel_iteration(A, b, x0)

print("\nSolusi:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])

Diagonally dominant:
[[ 10.   -3.    6.   24.5]
 [  1.    8.   -2.   -9. ]
 [ -2.    4.   -9.  -50. ]]
Iter |       x1       x2       x3 |     %ex1     %ex2     %ex3
   1 |   2.4500  -1.4312   4.3750 | 100.0000 100.0000 100.0000
   2 |  -0.6044   0.0443   5.7095 | 505.3775 3331.0406  23.3740
   3 |  -0.9624   0.4227   5.9573 |  37.2039  89.5203   4.1587
   4 |  -0.9976   0.4890   5.9946 |   3.5214  13.5634   0.6220
   5 |  -1.0000   0.4987   5.9994 |   0.2473   1.9313   0.0805

Converged.

Solusi:
x = -1.0000418689768602
y = 0.498650141213709
z = 5.999409366978728
